# Generated by Django 3.1.3 on 2021-01-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommodityService', '0002_auto_20210103_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='state',
            field=models.CharField(choices=[('TO_BE_REVIEWED', '待审核'), ('REJECTED', '未通过'), ('ON_THE_SHELVES', '已上架'), ('RESERVED', '已预定'), ('SALED', '已售出'), ('DELETED', '已删除')], default='TO_BE_REVIEWED', max_length=20),
        ),
        migrations.AlterField(
            model_name='commodityapplication',
            name='Commodity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CommodityService.commodity'),
        ),
    ]
