# Generated by Django 3.1.3 on 2021-01-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0005_auto_20210107_0221'),
        ('CommodityService', '0003_auto_20210107_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityapplication',
            name='auditor',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to='UserService.user'),
        ),
    ]
