# Generated by Django 3.1.3 on 2021-01-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderService', '0002_auto_20210103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('paying', '待付款'), ('paid', '已付款'), ('received', '已收货'), ('refunded', '已退款'), ('cancelled', '已取消')], default='待付款', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_platform',
            field=models.CharField(choices=[('alipay', '支付宝'), ('onlinebank', '网上银行'), ('wechat', '微信支付'), ('jingdongpay', '京东支付')], max_length=20, verbose_name='支付平台'),
        ),
    ]
