# Generated by Django 3.1.3 on 2021-01-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0005_auto_20210107_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='nick_name',
        ),
    ]
